version: '3.1'
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/wpdbpassword"
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: "wordpress"
    deploy:
      replicas: 1
    ports:
      - "80:80"
    secrets:
      - source: mysqlpassword
        target: wpdbpassword
        mode: 0400
    networks:
      - mysqlprivate

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysqlrootpassword"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysqlpassword"
      MYSQL_USER: "wordpress"
      MYSQL_DATABASE: "wordpress"
    deploy:
      replicas: 1
    secrets:
      - source: mysqlrootpassword
        target: mysqlrootpassword
      - source: mysqlpassword
        target: mysqlpassword
    networks:
      - mysqlprivate

networks:
  mysqlprivate:
    driver: overlay

secrets:
  mysqlpassword:
    external: true
  mysqlrootpassword:
    external: true